#!/usr/bin/env bash

# @license
# Copyright 2024-2026 Greg Lauckhart
# SPDX-License-Identifier: Apache-2.0

# Run Avahi in a loop.  This allows us to exec a kill command to clear the DNS cache

while true; do
    avahi-daemon --debug
    echo "*** AVAHI killed, restarting ***"
done
